### ISSUE TITLE
Bower asset path

### ISSUE THREAD

**Issue by k-timoshenko** [Dominus77/yii2-sweetalert2-widget#3]
Hi
In yii2 exist `@bower` alias. Use it instead of hardcoded path like this: `@vendor/bower-asset/sweetalert2/dist`
https://github.com/Dominus77/yii2-sweetalert2-widget/blob/master/assets/SweetAlert2Asset.php#L13

Some project may (and my) fail becouse of this.

**Comment by Dominus77** [comment]
Thank you, corrected.
