### ISSUE TITLE
Implementing array key value pairs in flash message

### ISSUE THREAD

**Issue by adummy832** [Dominus77/yii2-sweetalert2-widget#4]
hi @Dominus77 I wonder if i could do this in controller to flash message and use that in my view?
````
Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, [
    'title' => 'Your title',
    'text' => 'Your message'
]);
````

My View file is only a standard one.
````
<?= Alert::widget(['useSessionFlash' => true]) ?>
````

PS: Can't seem to find a handy way of doing this. Thank you.

**Comment by Dominus77** [comment]
Hi adummy832

Upgrade to version [1.3.1](https://github.com/Dominus77/yii2-sweetalert2-widget/tree/v1.3.1) and try:
```
Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, [
   [
       'title' => 'Your title',
       'text' => 'Your message'
   ]
]);
```
Two example:
```
Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, [
   [
       'title' => 'Your title',
       'text' => 'Your message',
       'timer' => 3000,
       'confirmButtonText' => 'Done!'
   ]
]);
```
Thank you.

**Comment by Dominus77** [comment]
Upgrade to version 1.3.2
More inforamation: https://github.com/Dominus77/yii2-sweetalert2-widget#flash-message

**Comment by adummy832** [comment]
Thank very much @Dominus77 , 
I'm using this as my primary flash message however can I pass extra data to it?
Like some api response along with the flash message.

````
Yii::$app->session->setFlash(Alert::TYPE_SUCCESS, [[
    'title' => 'Your title',
    'text' => 'Your message'
     ...
], [
    'your extra data' => JSON/String/Etc.
]]);
````

And how to access that extra data in the view?

This maybe an enhancement again, but thanks again for releasing 1.3.2! Cheers!

**Comment by Dominus77** [comment]
You can use callback.
As an example:
```
Yii::$app->session->setFlash('', [
[
    'title' => 'Are you sure?',
    'text' => "You won't be able to revert this!",
    'type' => Alert::TYPE_WARNING,
    'showCancelButton' => true,
    'confirmButtonColor' => '#3085d6',
    'cancelButtonColor' => '#d33',
    'confirmButtonText' => 'Yes, delete it!',
],
[
    'callback' => new \yii\web\JsExpression("
        function (result) {
            if(result.value) {
                swal('Deleted!','Your file has been deleted.','success')
            }
            if (result.dismiss === 'cancel') {
                swal(
                    'Cancelled',
                    'Your imaginary file is safe :)',
                    'error'
                 )
            }
        }
    "),
]
]);
```
More examples here: https://packagist.org/packages/dominus77/yii2-sweetalert2-widget
Also see Ajax request example.

**Comment by Dominus77** [comment]
I'm very pleased that you liked my extension, it gives me an incentive for its development)

**Comment by adummy832** [comment]
Of course man. I have integrated this extension in most of my projects bc the company i'm working w/ is fond of Yii2 Framework . Thanks again for this. Never thought of callbacks in PHP. 👍 👍
